

default:
  image: python:3.11

before_script:
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

stages:
  - test
  - build

testing:
  stage: test
  script:
    - pytest --junitxml=./reports/tests.xml
  artifacts:
    when: always
    reports:
      junit: ./reports/tests.xml

building:
  stage: build
  needs: [testing]
  script:
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - poetry config repositories.gitlab https://gitlab.laubenthal.me/api/v4/projects/7/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  when: manual
  # only:
  #   - /^release-.*$/