

default:
  image: python:3.11

before_script:
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

stages:
  - test
  - build

testing:
  stage: test
  script:
    - pytest --junitxml=./reports/tests.xml
  artifacts:
    when: always
    reports:
      junit: ./reports/tests.xml

building:
  stage: build
  needs: [testing]
  script:
    - poetry config repositories.gitlab https://gitlab.markuslaubenthal.de/api/v4/projects/1/packages/pypi
    - export VERSION=$(echo $CI_COMMIT_REF_NAME | sed 's/release-//')
    - poetry version $VERSION
    - poetry build
    - poetry publish --repository gitlab -u ${GITLAB_CI_USER} -p ${GITLAB_CI_TOKEN}
  only:
    - /^release-.*$/